name: Deploy and test

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      UTPLSQL_VERSION: v3.1.14
      UTPLSQL_CLI_VERSION: 3.1.9

    services:
      oracle:
        image: gvenzl/oracle-xe:21-slim
        env:
          DB_IMAGE: gvenzl/oracle-xe:21-slim
          ORACLE_PASSWORD: oracle
        ports:
          - 1521:1521
        options: >-
          --health-cmd healthcheck.sh
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install utPLSQL
        run: echo Installing ${UTPLSQL_VERSION} && sh ${{ github.workspace }}/scripts/1_install_utplsql.sh

      - name: Install utPLSQL-cli
        run: curl -Lk -o utPLSQL-cli.zip "https://github.com/utPLSQL/utPLSQL-cli/releases/download/${UTPLSQL_CLI_VERSION}/utPLSQL-cli.zip" && unzip utPLSQL-cli.zip && chmod -R u+x utPLSQL-cli

      - name: Install demo project
        run: sh ${{ github.workspace }}/scripts/2_install_demo_project.sh

      - name: Install unit tests
        run: sh ${{ github.workspace }}/scripts/3_install_tests.sh

      - name: Run unit tests
        run: sh ${{ github.workspace }}/scripts/4_run_tests.sh

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
